# https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml
version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
    - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    container_name: kibana
    ports:
    - "5601:5601"
    networks:
    - elk
    depends_on:
    - elasticsearch
networks:

  elk:
    driver: bridge
